# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e03e137de90d19901baf637004b5b0da"
application_url = "https://o5p1jotn5j.execute-api.us-east-1.amazonaws.com/dev"
embedded = true
name = "DropX"
handle = "dropx-3"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_customers,write_customers,read_products,write_products,read_analytics,read_checkouts,write_checkouts,read_marketing_events,write_marketing_events,read_companies,write_companies,read_discounts,write_discounts,read_draft_orders,write_draft_orders,read_fulfillments,write_fulfillments,read_inventory,write_inventory,read_locales,write_locales,read_locations,write_locations,read_price_rules,write_price_rules,read_reports,write_reports,read_resource_feedbacks,write_resource_feedbacks,read_script_tags,write_script_tags,read_shipping,write_shipping,read_themes,write_themes,read_payment_terms,write_payment_terms,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [
"https://o5p1jotn5j.execute-api.us-east-1.amazonaws.com/dev/shopify/auth",
"https://o5p1jotn5j.execute-api.us-east-1.amazonaws.com/dev/auth/callback",
"https://o5p1jotn5j.execute-api.us-east-1.amazonaws.com/dev/shopify/callback",
"https://o5p1jotn5j.execute-api.us-east-1.amazonaws.com/dev/api/auth/callback",
"https://o5p1jotn5j.execute-api.us-east-1.amazonaws.com/dev/post-install"
]

[pos]
embedded = false

[build]
dev_store_url = "quickstart-47141311.myshopify.com"
automatically_update_urls_on_dev = false
include_config_on_deploy = true
